//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace BuiltBroken.Team
{
	//http://www.rapidtables.com/web/color/RGB_Color.htm
	public class TeamData
	{
		public Color primary;
		public Color secondary;
		public String name;
	}
}

